# files are expected to be under config/staches/

# thanks to http://therantsandraves.com/?p=602 for these 'staches
-
  filename: party-hat.png
  scale_factor: 1.2
-
  filename: traffic-cone.png
  scale_factor: 1.7
